
/* "BOOK" 테이블 생성 */

CREATE TABLE "BOOK" (
	"BOOK_NO"	NUMBER		NOT NULL,
	"BOOK_TITLE"	NVARCHAR2(50)		NOT NULL,
	"BOOK_WRITER"	NVARCHAR2(20)		NOT NULL,
	"BOOK_PRICE"	NUMBER		NOT NULL,
	"REG_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "BOOK"."BOOK_NO" IS '책 번호';

COMMENT ON COLUMN "BOOK"."BOOK_TITLE" IS '책 제목';

COMMENT ON COLUMN "BOOK"."BOOK_WRITER" IS '글쓴이';

COMMENT ON COLUMN "BOOK"."BOOK_PRICE" IS '가격';

COMMENT ON COLUMN "BOOK"."REG_DATE" IS '등록일';

ALTER TABLE "BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY (
	"BOOK_NO"
);



SELECT * FROM BOOK;

---------------------

-- INSERT


-- 책 번호 시퀀스 만들기 
CREATE SEQUENCE SEQ_BOOK_NO NOCACHE;

-- 샘플 도서 데이터 삽입
INSERT INTO "BOOK" VALUES(SEQ_BOOK_NO.NEXTVAL, '어린왕자', '생택쥐베리', 8000, DEFAULT);

INSERT INTO "BOOK" VALUES(SEQ_BOOK_NO.NEXTVAL, '자바의 정석', '남궁 성', 30000, DEFAULT);

-- 전체 도서 조회
SELECT BOOK_NO, BOOK_TITLE, BOOK_WRITER, BOOK_PRICE, TO_CHAR(REG_DATE, 'YYYY-MM-DD')
FROM "BOOK";

-- 도서 등록
INSERT INTO "BOOK" VALUES(SEQ_BOOK_NO.NEXTVAL, '존윅', '생택', 15000, DEFAULT)













